### ISSUE TITLE
Graceful pre-stop to allow agents to de-register. 

### ISSUE THREAD

**Issue by BenCoughlan15** [jitterbit/charts#5]
**https://blog.gruntwork.io/gracefully-shutting-down-pods-in-a-kubernetes-cluster-328aecec90d**

Please see above. 

Currently, we're getting unknown/stuck agents, jitterbit mothership doesn't seem to recognise this or how to handle it, and the chart doesn't have a pre-stop command.

**Comment by sean-krail** [comment]
Hi @BenCoughlan15, thanks for the article. The Docker agent does graceful shutdown through trapping the term/kill signals. We do this instead of using the preStop hook so that it's platform agnostic (will work as vanilla Docker, Docker Swarm, ECS, Kubernetes, etc.).

There are two situations I can think of where the agent won't deregister properly:
1. Make sure that `deregisterAgentOnDrainstop` is set to `true`. https://github.com/jitterbit/charts/blob/ca5c8130dcecd71f8fd6afc5ae545f725144cb91/charts/agent-group/values.yaml#L21
2. The agent is failing to startup properly (that would be an issue with the agent itself or misconfiguration). This is a difficult problem to solve at the moment since the <=10.20 Docker agent's don't output much to stdout/err. In 10.21 the Docker agent will be outputting much more to stdout, making this situation easier to debug.
